/* f - Decompiled by JODE
 * Visit http://jode.sourceforge.net/
 */
package jagdx;

public class f
{
    public static int r = 0;
    public static int j = 16;
    public static int i = 32;
    public static int p = 64;
    static int o = 1;
    public static int s = 1;
    public static int f = 0;
    public static int z = 2;
    public static int w = 0;
    public static int n = 1;
    public static int l = 2;
    public static int b = 3;
    public static int k = 4;
    public static int q = 5;
    public static int u = 6;
    public static int x = 24;
    public static int g = 26;
    public static int d = 27;
    public static int c = 1;
    public static int a = 2;
    public static int e = 4;
    public static int m = 7;
    public static int t = 10;
    public static int h = 26;
    public static int y = 0;
    public static int v = 1;
    public static int ay = 2;
    public static int ac = 3;
    public static int al = 16;
    public static int at = 32;
    public static int aw = 0;
    public static int ap = 1;
    public static int ai = 2;
    public static int as = 3;
    public static int aj = 4;
    public static int ax = 256;
    public static int ad = 0;
    public static int an = 1;
    public static int af = 1;
    public static int aq = 2;
    public static int aa = 512;
    public static int ab = 16;
    public static int ak = 8192;
    public static int ag = 1024;
    public static int az = 8;
    public static int ah = 7;
    public static int av = 8;
    public static int ar = 9;
    public static int am = 14;
    public static int au = 15;
    public static int ae = 19;
    public static int ao = 20;
    public static int bg = 22;
    public static int bs = 23;
    public static int bo = 24;
    public static int bt = 25;
    public static int bc = 27;
    public static int bf = 28;
    public static int bl = 34;
    public static int bk = 35;
    public static int br = 36;
    public static int bi = 37;
    public static int bz = 38;
    public static int be = 60;
    public static int by = 137;
    public static int bp = 145;
    public static int bx = 147;
    public static int ba = 154;
    public static int bm = 161;
    public static int bq = 168;
    public static int bn = 174;
    public static int bu = 206;
    public static int bv = 207;
    public static int bw = 208;
    public static int bj = 2;
    public static int bh = 1;
    public static int bd = 1;
    public static int bb = 2;
    public static int ch = 3;
    public static int ce = 4;
    public static int cz = 5;
    public static int cj = 6;
    public static int cy = 4;
    public static int cb = 5;
    public static int ct = 1;
    public static int cd = 2;
    public static int cn = 5;
    public static int co = 6;
    public static int cm = 7;
    public static int cw = 0;
    public static int cq = 1;
    public static int ci = 2;
    public static int cs = 2;
    public static int cr = 2;
    public static int cv = 3;
    public static int ck = 1;
    public static int cl = 2;
    public static int cp = 5;
    public static int cf = 6;
    public static int cu = 9;
    public static int ca = 1;
    public static int cg = 3;
    public static int cx = 1;
    public static int cc = 3;
    public static int db = 3;
    public static int ds = 1;
    public static int dg = 3;
    public static int dz = 4;
    
    private f() throws Throwable {
	throw new Error();
    }
}
